version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-user-auth
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=golang_user_auth

  db:
    image: postgres:15
    container_name: user-auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: golang_user_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
